Lecture/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("akbar", views.akbar, name="akbar"),
    path("<str:name>", views.greet, name="greet")
]    

Lecture/sumpahpemuda/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

Lecture/task/urls.py
from django.urls import path

from . import views

app_name = 'task'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add')
]

Lecture/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def akbar(request):
    return HttpResponse("Hello, Akbar!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name" : name.capitalize()
    })

Lecture/sumpahpemuda/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, 'sumpahpemuda/index.html', {
        "sumpahpemuda" : now.month == 10 and now.day == 10
    })

    

Lecture/task/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render



class NewTaskForm(forms.Form):
    task = forms.CharField(label="Daftar baru")
    

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, 'task/index.html', {
        "task": request.session["tasks"]
    })

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse('task:index'))
        else:
            return render(request, 'task/add.html', {
                "form": form
            })

    return render(request, 'task/add.html', {
        "form": NewTaskForm()
    })

Lecture/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>heloo</title>
</head>
<body>
    <h1>Hello, {{ name }}</h1>
</body>
</html>

Lecture/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, World!</h1>
    <h2>gerakan ranmahan</h2>
</body>
</html>

Lecture/sumpahpemuda/templates/sumpahpemuda/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Apakah hari ini sumpah pemuda</title>
    <link href="{% static 'sumpahpemuda/styles.css' %}"  rel="stylesheet">
</head>
<body>
    {% if sumpahpemuda %}
        <h1>Ya</h1>
    {% else %}
        <h1>tidak</h1>
    {% endif %}
</body>
</html>

Lecture/task/templates/task/add.html
{% extends "task/layout.html" %}

{% block body %}
    <h1>Tambah Daftar</h1>
        <form action="{% url 'task:add' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
    <a href="{% url 'task:index' %}">Index</a>
{% endblock %}

Lecture/task/templates/task/index.html
{% extends "task/layout.html" %}

{% block body %}
<h1>Daftar Pekerjaan</h1>
    <ul>
        {% for daftar in task %}
            <li>{{ daftar }}</li>

        {% endfor %}
    </ul>
    <a href="{% url 'task:add' %}">Tambah</a>
{% endblock %}

Lecture/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>